-- All values were generated by AI Assistant

-- Insert Users
INSERT INTO Users (FirstName, LastName, PhoneNumber, Email, Password, DateOfBirth)
VALUES ('John', 'Doe', '+380123456789', 'john.doe@student.ztu.edu.ua', 'password1', '1992-01-15'),
       ('Jane', 'Smith', '+380987654321', 'jane.smith@gmail.com', 'password2', '1994-02-20'),
       ('Alice', 'Johnson', '+380135791357', 'alice.johnson@gmail.com', 'password3', '2001-03-25'),
       ('Bob', 'Brown', '+380246802468', 'bob.brown@gmail.com', 'password4', '1990-04-30'),
       ('Charlie', 'Davis', '+380369874123', 'charlie.davis@gmail.com', 'password5', '1995-05-05'),
       ('Diana', 'Wilson', '+380482016357', 'diana.wilson@student.ztu.edu.ua', 'password6', '2000-06-10'),
       ('Ethan', 'Martinez', '+380593017246', 'ethan.martinez@gmail.com', 'password7', '1993-07-15'),
       ('Fiona', 'Garcia', '+380604826139', 'fiona.garcia@gmail.com', 'password8', '2004-08-20'),
       ('George', 'Moore', '+380715946280', 'george.moore@student.ztu.edu.ua', 'password9', '1997-09-25'),
       ('Hannah', 'Taylor', '+380826135790', 'hannah.taylor@student.ztu.edu.ua', 'password10', '1998-10-30'),
       ('Isaac', 'Anderson', '+380937246801', 'isaac.anderson@gmail.com', 'password11', '1991-11-05'),
       ('Jack', 'Thomas', '+380148359260', 'jack.thomas@gmail.com', 'password12', '1996-12-10'),
       ('Katherine', 'Jackson', '+380259460370', 'katherine.jackson@gmail.com', 'password13', '2003-01-15'),
       ('Liam', 'White', '+380370571480', 'liam.white@gmail.com', 'password14', '1999-02-20'),
       ('Mia', 'Harris', '+380481682591', 'mia.harris@gmail.com', 'password15', '2005-03-25');

-- Insert Merchants
INSERT INTO Merchants (Name, Number)
VALUES ('YouTube', '678901'),
       ('Spotify', '123456'),
       ('Netflix', '234567'),
       ('Amazon', '345678'),
       ('Hulu', '456789'),
       ('DisneyPlus', '567890'),
       ('Apple', '678912'),
       ('Microsoft', '789023'),
       ('Google', '890134'),
       ('Facebook', '901245');
-- Insert Online Services
INSERT INTO OnlineServices (Name, MerchantId)
VALUES ('YouTube Premium', 1),
       ('Spotify Premium', 2),
       ('Netflix Basic', 3),
       ('Netflix Standard', 3),
       ('Netflix Premium', 3),
       ('Amazon Prime', 4),
       ('Hulu No Ads', 5),
       ('Disney+ Bundle', 6),
       ('Apple Music', 7),
       ('Microsoft 365', 8),
       ('Google Drive', 9),
       ('Facebook Ads', 10);


-- Insert Locations
INSERT INTO Locations (City, Address)
VALUES ('Kyiv', 'Khreshchatyk St, 1'),
       ('Kyiv', 'Velyka Vasylkivska St, 55'),
       ('Lviv', 'Svobody Ave, 28'),
       ('Lviv', 'Halytska St, 12'),
       ('Odesa', 'Deribasivska St, 10'),
       ('Odesa', 'Primorsky Blvd, 23'),
       ('Dnipro', 'Dmytro Yavornytskyi Ave, 59'),
       ('Dnipro', 'Karla Marksa Ave, 87'),
       ('Kharkiv', 'Sumska St, 35'),
       ('Kharkiv', 'Pushkinska St, 40');
-- Insert ATMs
INSERT INTO ATMs (Balance, WorkStatus, LocationId)
VALUES (50000.00, 'Online', 1),
       (30000.00, 'Online', 2),
       (20000.00, 'Offline', 3),
       (45000.00, 'Online', 4),
       (25000.00, 'Maintenance', 5),
       (60000.00, 'Online', 6),
       (35000.00, 'Low Cash', 7),
       (48000.00, 'Online', 8),
       (15000.00, 'Out of Cash', 9),
       (5000.00, 'Online', 10);


-- Insert Cards
INSERT INTO Cards (Balance, Number, CVV, Pin, IsBlocked, ExpirationDate, Currency, UserId)
VALUES (1000.50, '1234567812345678', '123', '1111', 0, '2025-12-31', 'USD', 1),
       (250.75, '2345678923456789', '234', '2222', 0, '2026-01-30', 'EUR', 2),
       (3400.00, '3456789034567890', '345', '3333', 1, '2027-02-28', 'UAH', 3),
       (425.60, '4567890145678901', '456', '4444', 0, '2025-03-31', 'USD', 4),
       (980.20, '5678901256789012', '567', '5555', 0, '2026-04-30', 'EUR', 5),
       (1500.00, '6789012367890123', '678', '6666', 1, '2027-05-31', 'UAH', 6),
       (75.15, '7890123478901234', '789', '7777', 0, '2025-06-30', 'USD', 7),
       (300.80, '8901234589012345', '890', '8888', 0, '2026-07-31', 'EUR', 8),
       (1200.00, '9012345690123456', '901', '9999', 1, '2027-08-31', 'UAH', 9),
       (450.45, '0123456701234567', '012', '1010', 0, '2025-09-30', 'USD', 10),
       (875.25, '1234567812345679', '123', '1212', 0, '2026-10-31', 'EUR', 11),
       (400.00, '2345678923456790', '234', '1313', 1, '2027-11-30', 'UAH', 12),
       (3200.35, '3456789034567901', '345', '1414', 0, '2025-12-31', 'USD', 13),
       (525.50, '4567890145678912', '456', '1515', 0, '2026-01-30', 'EUR', 14),
       (1025.00, '5678901256789023', '567', '1616', 1, '2027-02-28', 'UAH', 15);
-- Insert Transactions
INSERT INTO Transactions (Amount, TimeStamp, Status, CardId, CardBalance, TransactionType, ATMId, OnlineServiceId, ServiceReceiptNumber, RecipientCardId, RecipientCardBalance, ATMTransactionType)
VALUES
    -- March 15 transactions
    (150.00, '2024-03-15 10:30:00', 'Success', 1, 850.50, 'ATM', 1, NULL, NULL, NULL, NULL, 'Withdraw'),
    (14.99, '2024-03-15 11:20:00', 'Success', 2, 235.76, 'OnlineService', NULL, 1, 'P123457', NULL, NULL, NULL),
    (500.00, '2024-03-15 12:15:00', 'Success', 3, 2900.00, 'Transfer', NULL, NULL, NULL, 4, 925.60, NULL),
    (19.99, '2024-03-15 13:45:00', 'Success', 5, 405.61, 'OnlineService', NULL, 3, 'P123459', NULL, NULL, NULL),
    (200.00, '2024-03-15 14:30:00', 'Success', 6, 780.20, 'ATM', 2, NULL, NULL, NULL, NULL, 'Withdraw'),
    (9.99, '2024-03-15 15:20:00', 'Failed', 7, 1490.01, 'ATM', 2, NULL, NULL, NULL, NULL, 'Deposit'),
    (300.00, '2024-03-15 16:10:00', 'Success', 8, 375.15, 'Transfer', NULL, NULL, NULL, 9, 600.80, NULL),
    (15.99, '2024-03-15 17:00:00', 'Pending', 10, 284.81, 'OnlineService', NULL, 4, 'P123463', NULL, NULL, NULL),
    (100.00, '2024-03-15 18:15:00', 'Success', 11, 1100.00, 'ATM', 3, NULL, NULL, NULL, NULL, 'Deposit'),
    (29.99, '2024-03-15 19:30:00', 'Cancelled', 12, 420.46, 'OnlineService', NULL, 5, 'P123465', NULL, NULL, NULL),
    -- March 16 transactions
    (75.50, '2024-03-16 09:15:00', 'Success', 13, 3124.85, 'ATM', 4, NULL, NULL, NULL, NULL, 'Withdraw'),
    (17.99, '2024-03-16 10:30:00', 'Success', 14, 507.51, 'OnlineService', NULL, 6, 'P123466', NULL, NULL, NULL),
    (250.00, '2024-03-16 11:45:00', 'Success', 15, 775.00, 'Transfer', NULL, NULL, NULL, 1, 1100.50, NULL),
    (13.99, '2024-03-16 12:20:00', 'Success', 1, 836.51, 'OnlineService', NULL, 7, 'P123467', NULL, NULL, NULL),
    (180.00, '2024-03-16 13:40:00', 'Success', 2, 55.76, 'ATM', 5, NULL, NULL, NULL, NULL, 'Withdraw'),
    (45.00, '2024-03-16 14:15:00', 'Success', 3, 2855.00, 'Transfer', NULL, NULL, NULL, 4, 970.60, NULL),
    (19.99, '2024-03-16 15:30:00', 'Failed', 4, 405.61, 'OnlineService', NULL, 8, 'P123468', NULL, NULL, NULL),
    (300.00, '2024-03-16 16:45:00', 'Success', 5, 480.20, 'ATM', 6, NULL, NULL, NULL, NULL, 'Withdraw'),
    (11.99, '2024-03-16 17:20:00', 'Success', 6, 768.21, 'OnlineService', NULL, 9, 'P123469', NULL, NULL, NULL),
    (150.00, '2024-03-16 18:30:00', 'Success', 7, 225.15, 'Transfer', NULL, NULL, NULL, 8, 750.80, NULL),
    -- March 17 transactions
    (14.99, '2024-03-17 09:00:00', 'Success', 8, 269.82, 'OnlineService', NULL, 10, 'P123470', NULL, NULL, NULL),
    (250.00, '2024-03-17 10:15:00', 'Success', 9, 850.00, 'ATM', 7, NULL, NULL, NULL, NULL, 'Deposit'),
    (9.99, '2024-03-17 11:30:00', 'Success', 10, 410.47, 'OnlineService', NULL, 11, 'P123471', NULL, NULL, NULL),
    (400.00, '2024-03-17 12:45:00', 'Success', 11, 475.25, 'Transfer', NULL, NULL, NULL, 12, 800.00, NULL),
    (16.99, '2024-03-17 13:20:00', 'Pending', 12, 383.01, 'OnlineService', NULL, 12, 'P123472', NULL, NULL, NULL),
    (175.00, '2024-03-17 14:30:00', 'Success', 13, 2949.85, 'ATM', 8, NULL, NULL, NULL, NULL, 'Withdraw'),
    (13.99, '2024-03-17 15:45:00', 'Success', 14, 493.52, 'OnlineService', NULL, 1, 'P123473', NULL, NULL, NULL),
    (200.00, '2024-03-17 16:20:00', 'Success', 15, 575.00, 'Transfer', NULL, NULL, NULL, 1, 1300.50, NULL),
    (19.99, '2024-03-17 17:30:00', 'Success', 1, 816.52, 'OnlineService', NULL, 2, 'P123474', NULL, NULL, NULL),
    (125.00, '2024-03-17 18:45:00', 'Success', 2, 930.76, 'ATM', 9, NULL, NULL, NULL, NULL, 'Deposit'),
    -- March 18 transactions
    (14.99, '2024-03-18 09:15:00', 'Success', 3, 2840.01, 'OnlineService', NULL, 3, 'P123475', NULL, NULL, NULL),
    (350.00, '2024-03-18 10:30:00', 'Success', 4, 55.61, 'Transfer', NULL, NULL, NULL, 5, 830.20, NULL),
    (9.99, '2024-03-18 11:45:00', 'Failed', 5, 820.21, 'OnlineService', NULL, 4, 'P123476', NULL, NULL, NULL),
    (225.00, '2024-03-18 12:20:00', 'Success', 6, 543.21, 'ATM', 10, NULL, NULL, NULL, NULL, 'Withdraw'),
    (17.99, '2024-03-18 13:30:00', 'Success', 7, 207.16, 'OnlineService', NULL, 5, 'P123477', NULL, NULL, NULL),
    (275.00, '2024-03-18 14:45:00', 'Success', 8, 994.82, 'Transfer', NULL, NULL, NULL, 9, 1125.00, NULL),
    (13.99, '2024-03-18 15:20:00', 'Success', 9, 836.01, 'OnlineService', NULL, 6, 'P123478', NULL, NULL, NULL),
    (150.00, '2024-03-18 16:30:00', 'Success', 10, 260.47, 'ATM', 1, NULL, NULL, NULL, NULL, 'Withdraw'),
    (19.99, '2024-03-18 17:45:00', 'Pending', 11, 455.26, 'OnlineService', NULL, 7, 'P123479', NULL, NULL, NULL),
    (325.00, '2024-03-18 18:20:00', 'Success', 12, 58.01, 'Transfer', NULL, NULL, NULL, 13, 3274.85, NULL);


